// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxTVJs3Sr10eiIg9PjYSSDZmlCmQAkK3o',
    appId: '1:637460307843:web:ba5a0df594717f0597e0b6',
    messagingSenderId: '637460307843',
    projectId: 'clone-b7d86',
    authDomain: 'clone-b7d86.firebaseapp.com',
    storageBucket: 'clone-b7d86.appspot.com',
    measurementId: 'G-2DXBWNTN4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTo1XycYPI_S0S8ygcbzknLg-9f0pGbU',
    appId: '1:637460307843:android:fba7a5e5d760d49f97e0b6',
    messagingSenderId: '637460307843',
    projectId: 'clone-b7d86',
    storageBucket: 'clone-b7d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrh2t9sBWnF8xwbw1uvd7y_ZSuPbCYrHg',
    appId: '1:637460307843:ios:5ab560eb1c78ee4797e0b6',
    messagingSenderId: '637460307843',
    projectId: 'clone-b7d86',
    storageBucket: 'clone-b7d86.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrh2t9sBWnF8xwbw1uvd7y_ZSuPbCYrHg',
    appId: '1:637460307843:ios:5ab560eb1c78ee4797e0b6',
    messagingSenderId: '637460307843',
    projectId: 'clone-b7d86',
    storageBucket: 'clone-b7d86.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxTVJs3Sr10eiIg9PjYSSDZmlCmQAkK3o',
    appId: '1:637460307843:web:e4dadc63e84f366c97e0b6',
    messagingSenderId: '637460307843',
    projectId: 'clone-b7d86',
    authDomain: 'clone-b7d86.firebaseapp.com',
    storageBucket: 'clone-b7d86.appspot.com',
    measurementId: 'G-33DH16X1N4',
  );
}
